function matlabbatch = add_contrasts(spm_path, cons_model, cons_model_name, runs, delete_flag)
    % add_contrasts - create contrasts for a first-level SPM.mat
    % spm_path: full path to SPM.mat
    % cons_model: cell array of contrast expressions (e.g. {'ImagexValue'})
    % cons_model_name: cell array of contrast names
    % runs: cell array of run indices as strings
    % delete_flag: 1 to delete existing contrasts, 0 to append

    if nargin < 5
        delete_flag = 1;
    end

    if ~exist(spm_path, 'file')
        error('SPM.mat not found: %s', spm_path);
    end

    load(spm_path);
    name_list = SPM.xX.name;

    matlabbatch = {};
    matlabbatch{1}.spm.stats.con.spmmat = cellstr(spm_path);

    for c = 1:length(cons_model)
        cons = cons_model{c};
        cons_name = cons_model_name{c};

        % Collect all matching columns across ALL sessions (Sn(1) .. Sn(N))
        % Accept both '^1*bf(1)' and '*bf(1)' suffix forms generated by SPM
        pattern_with_pow = ['^Sn\(\d+\) ', cons, '\^1\*bf\(1\)$'];
        pattern_plain    = ['^Sn\(\d+\) ', cons, '\*bf\(1\)$'];
        idx_with_pow = ~cellfun('isempty', regexp(name_list, pattern_with_pow));
        idx_plain    = ~cellfun('isempty', regexp(name_list, pattern_plain));
        idx_logical  = idx_with_pow | idx_plain;
        idx = find(idx_logical);

        if isempty(idx)
            warning('add_contrasts:NoColumnsFound', ...
                'No matching columns found for contrast "%s" in SPM.xX.name. Check regressor names.', cons);
        end

        con_vec = zeros(1,length(name_list));
        con_vec(idx) = 1;

        matlabbatch{1}.spm.stats.con.consess{c}.tcon.name = cons_name;
        matlabbatch{1}.spm.stats.con.consess{c}.tcon.convec = con_vec;
        matlabbatch{1}.spm.stats.con.consess{c}.tcon.sessrep = 'none';
    end

    matlabbatch{1}.spm.stats.con.delete = delete_flag;

end
